INSERT INTO Course (course_code, course_name, teacher_assigned)
VALUES 
('CS101', 'Introduction to Computer Science', 'Dr. Smith'),
('MATH202', 'Calculus II', 'Prof. Johnson'),
('ENG101', 'English Composition', 'Prof. Brown'),
('HIST103', 'World History', 'Dr. Jones'),
('CHEM201', 'Organic Chemistry', 'Prof. White'),
('PHYS101', 'Physics I', 'Dr. Adams'),
('ART105', 'Introduction to Art', 'Prof. Moore'),
('PSYC201', 'Introduction to Psychology', 'Dr. Davis'),
('BIOL101', 'Biology', 'Dr. Taylor'),
('MUSC110', 'Music Appreciation', 'Prof. Allen'),
('PHIL101', 'Introduction to Philosophy', 'Prof. Martinez'),
('GEOL101', 'Geology', 'Dr. Rodriguez'),
('ECON101', 'Principles of Economics', 'Dr. King'),
('LANG101', 'Foreign Language: Spanish', 'Prof. Garcia'),
('STAT101', 'Statistics', 'Prof. Nguyen'),
('BUS101', 'Introduction to Business', 'Dr. Evans'),
('SOC101', 'Introduction to Sociology', 'Prof. Thompson'),
('ANTH101', 'Introduction to Anthropology', 'Dr. Clark'),
('POL101', 'Political Science', 'Prof. Carter'),
('CHEM102', 'General Chemistry', 'Prof. Adams'),
('PHYS102', 'Physics II', 'Dr. White'),
('ENG102', 'English Literature', 'Prof. Roberts'),
('MATH203', 'Multivariable Calculus', 'Prof. Smith'),
('CS102', 'Data Structures', 'Dr. Johnson'),
('PHYS103', 'Modern Physics', 'Prof. Moore'),
('ART106', 'Art History', 'Dr. Garcia'),
('PSYC202', 'Developmental Psychology', 'Prof. Martinez'),
('BIOL102', 'Ecology', 'Dr. Rodriguez'),
('MUSC111', 'Music Theory', 'Prof. Allen'),
('PHIL102', 'Ethics', 'Prof. Nguyen'),
('GEOL102', 'Oceanography', 'Dr. King'),
('ECON102', 'Microeconomics', 'Dr. Garcia'),
('LANG102', 'Foreign Language: French', 'Prof. Martinez'),
('STAT102', 'Regression Analysis', 'Prof. Nguyen'),
('BUS102', 'Management Principles', 'Dr. Evans'),
('SOC102', 'Cultural Anthropology', 'Dr. Clark'),
('ANTH102', 'Archaeology', 'Prof. Carter'),
('POL102', 'International Relations', 'Dr. Thompson'),
('CHEM103', 'Inorganic Chemistry', 'Dr. Adams'),
('PHYS104', 'Quantum Mechanics', 'Prof. White'),
('ENG103', 'Creative Writing', 'Prof. Roberts'),
('MATH204', 'Differential Equations', 'Dr. Smith'),
('CS103', 'Database Management Systems', 'Dr. Johnson'),
('PHYS105', 'Astrophysics', 'Prof. Moore'),
('ART107', 'Renaissance Art', 'Dr. Garcia'),
('PSYC203', 'Abnormal Psychology', 'Prof. Martinez'),
('BIOL103', 'Genetics', 'Dr. Rodriguez'),
('MUSC112', 'Music History', 'Prof. Allen'),
('PHIL103', 'Logic', 'Prof. Nguyen'),
('GEOL103', 'Volcanology', 'Dr. King'),
('ECON103', 'Macroeconomics', 'Dr. Garcia'),
('LANG103', 'Foreign Language: German', 'Prof. Martinez'),
('STAT103', 'Hypothesis Testing', 'Prof. Nguyen'),
('BUS103', 'Marketing Management', 'Dr. Evans'),
('SOC103', 'Social Psychology', 'Dr. Clark'),
('ANTH103', 'Cultural Studies', 'Prof. Carter'),
('POL103', 'Comparative Politics', 'Dr. Thompson'),
('CHEM104', 'Biochemistry', 'Dr. Adams'),
('PHYS106', 'Nuclear Physics', 'Prof. White'),
('ENG104', 'American Literature', 'Prof. Roberts'),
('MATH205', 'Linear Algebra', 'Dr. Smith'),
('CS104', 'Computer Networks', 'Dr. Johnson'),
('PHYS107', 'Particle Physics', 'Prof. Moore'),
('ART108', 'Modern Art', 'Dr. Garcia'),
('PSYC204', 'Cognitive Psychology', 'Prof. Martinez'),
('BIOL104', 'Cell Biology', 'Dr. Rodriguez'),
('MUSC113', 'Opera History', 'Prof. Allen'),
('PHIL104', 'Metaphysics', 'Prof. Nguyen'),
('GEOL104', 'Mineralogy', 'Dr. King'),
('ECON104', 'Game Theory', 'Dr. Garcia'),
('LANG104', 'Foreign Language: Mandarin', 'Prof. Martinez'),
('STAT104', 'ANOVA', 'Prof. Nguyen'),
('BUS104', 'Financial Accounting', 'Dr. Evans'),
('SOC104', 'Deviance and Social Control', 'Dr. Clark'),
('ANTH104', 'Primate Behavior', 'Prof. Carter'),
('POL104', 'Public Policy', 'Dr. Thompson'),
('CHEM105', 'Physical Chemistry', 'Dr. Adams'),
('PHYS108', 'Cosmology', 'Prof. White'),
('ENG105', 'British Literature', 'Prof. Roberts'),
('MATH206', 'Discrete Mathematics', 'Dr. Smith'),
('CS105', 'Software Engineering', 'Dr. Johnson');